__version__ = "0.0.1"
AUTHOR = "Guillermo Adrián Molina"
AUTHOR_EMAIL = "guillermoadrianmolina@gmail.com"
NAME = "prototype-language"
PACKAGE_URL = "https://github.com/guillermomolina/prototype-language/"
KEYWORDS = "prototype language"
DESCRIPTION = "Prototype LAnguage"
LICENSE = "LICENSE"
